// USERS TYPES
export const GET_ADMIN_ALL_USERS_REQUEST = 'GET_ADMIN_ALL_USERS_REQUEST'
export const GET_ADMIN_ALL_USERS_SUCCESS = 'GET_ADMIN_ALL_USERS_SUCCESS'
export const GET_ADMIN_ALL_USERS_FAIL = 'GET_ADMIN_ALL_USERS_FAIL'

export const GET_ADMIN_SINGLE_USERS_REQUEST = 'GET_ADMIN_SINGLE_USERS_REQUEST'
export const GET_ADMIN_SINGLE_USERS_SUCCESS = 'GET_ADMIN_SINGLE_USERS_SUCCESS'
export const GET_ADMIN_SINGLE_USERS_FAIL = 'GET_ADMIN_SINGLE_USERS_FAIL'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_RESET = 'DELETE_USER_RESET'
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'


// PRODUCT TYPES
export const GET_ADMIN_ALL_PRODUCTS_REQUEST = 'GET_ADMIN_ALL_PRODUCTS_REQUEST'
export const GET_ADMIN_ALL_PRODUCTS_SUCCESS = 'GET_ADMIN_ALL_PRODUCTS_SUCCESS'
export const GET_ADMIN_ALL_PRODUCTS_FAIL = 'GET_ADMIN_ALL_PRODUCTS_FAIL'

export const CREATE_ADMIN_PRODUCT_REQUEST = 'CREATE_ADMIN_PRODUCT_REQUEST'
export const CREATE_ADMIN_PRODUCT_SUCCESS = 'CREATE_ADMIN_PRODUCT_SUCCESS'
export const CREATE_ADMIN_PRODUCT_FAIL = 'CREATE_ADMIN_PRODUCT_FAIL'

// ORDERS TYPES
export const GET_ADMIN_ALL_ORDERS_REQUEST = 'GET_ADMIN_ALL_ORDERS _REQUEST'
export const GET_ADMIN_ALL_ORDERS_SUCCESS = 'GET_ADMIN_ALL_ORDERS_SUCCESS'
export const GET_ADMIN_ALL_ORDERS_FAIL = 'GET_ADMIN_ALL_ORDERS_FAIL'


export const CLEAR_ERROR = "CLEAR_ERROR"