export const ALL_ORDERS_GET_REQEST = "ALL_ORDERS_GET_REQEST"
export const ALL_ORDERS_GET_SUCCESS = "ALL_ORDERS_GET_SUCCESS"
export const ALL_ORDERS_GET_FAIL = "ALL_ORDERS_GET_FAIL"


export const USER_ORDERS_GET_REQEST = "USER_ORDERS_GET_REQEST"
export const USER_ORDERS_GET_SUCCESS = "USER_ORDERS_GET_SUCCESS"
export const USER_ORDERS_GET_FAIL = "USER_ORDERS_GET_FAIL"


export const SINGLE_ORDER_GET_REQEST = "SINGLE_ORDERS_GET_REQEST"
export const SINGLE_ORDER_GET_SUCCESS = "SINGLE_ORDERS_GET_SUCCESS"
export const SINGLE_ORDER_GET_FAIL = "SINGLE_ORDERS_GET_FAIL"

export const NEW_ORDER_CREATE_REQUEST = "NEW_ORDER_CREATE_REQUEST"
export const NEW_ORDER_CREATE_SUCCESS = "NEW_ORDER_CREATE_SUCCESS"
export const NEW_ORDER_CREATE_FAIL = "NEW_ORDER_CREATE_FAIL"
export const NEW_ORDER_CREATE_RESET = "NEW_ORDER_CREATE_RESET"

export const CLEARE_ERROR = "CLEARE ERROR"