export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST"
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL"

export const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST "
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS "
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL "

export const PRODUCT_REVIEW_CREATE_SUCCESS = "PRODUCT_REVIEW_CREATE_SUCCESS"
export const PRODUCT_REVIEW_CREATE_FAIL = "PRODUCT_REVIEW_CREATE_FAIL"

export const PRODUCT_REVIEW_RESET = "PRODUCT_REVIEW_RESET"

export const CLEAR_ERROR = "CLEAR_ERROR"